name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout to the repo"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup node"
        uses: actions/setup-node@v4
        with: { node-version: "20" }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
